### ISSUE TITLE
Please delete

### ISSUE THREAD

**Issue by jefflongo** [gmherr2/AwSMS_IssueTracker#11]
Heads up notification setting swipe to mark as read just removes the notification but the message is still unread.

Awsms beta 1.0
Galaxy Note5
Lollipop 5.1.1

**Comment by gmherr2** [comment]
That only works for the heads up quick reply not the Built in Android Notifications

**Comment by jefflongo** [comment]
What do you mean? I'm using the heads up quick reply. If it is intended not
to work then what is the difference between mark as read and dismiss?

**Comment by gmherr2** [comment]
Ok thought you were referring to stock heads up. I tried replicating this issue with quick reply heads up but it was marking them as read. I will have to look more into this! Thanks

**Comment by jefflongo** [comment]
Oh I see.  If I first drag down the heads up to quick reply and then swipe it away it marks as read.  Sorry about that, you can close this.  Thanks for the clarification.
