### ISSUE TITLE
Beginning of entries are not capitalized.

### ISSUE THREAD

**Issue by drtwin32** [gmherr2/AwSMS_IssueTracker#13]
AwSMS Beta 1.1, Nexus 5, Android 6.0.1

Start a new conversation or enter an existing one. When beginning to type a response, the first letter is not automatically capitalized. This only seems to happen in AwSMS.

**Comment by TechnoSparks** [comment]
I can confirm, but this happens on the text field itself, all the text is in undercase, in my case.

I am using Xperia Keyboard.

**Comment by Brentonkruger** [comment]
Confirmed on one plus two using Google keyboard. Tested in other apps, but awsms is the only one.
