### ISSUE TITLE
White Square Icon for Ticker Notification

### ISSUE THREAD

**Issue by TechnoSparks** [gmherr2/AwSMS_IssueTracker#2]
### Brief description

If a new message is received, the icon is a white square (I assume it should be a message bubble icon).
### Replication method
1. Receive a text message
2. Enable ticker notification settings if on custom ROM
3. Look at status bar when the ticker notification is scrolling
### Details

Sony Xperia SP
AICP Lollipop 16th December Nightly (yes, custom ROM, CyanogenMod based)
Bug still persist on version Beta 1.1 (apk on G+ community)
### Other notes

I haven't able yet to find anyone with the same problem as mine.. Maybe I am a minority. Also I am unable to find someone with the same device to help me. Consider this issue less important, but I would really love to see it being squashed one day ;) Original report on G+ is [here](https://plus.google.com/+ShahmiSaidi/posts/EcDSAaa3ooY)
### Example screenshot

![2015 - 1](https://cloud.githubusercontent.com/assets/6072210/12370945/cd9284be-bc5e-11e5-9b05-c22611fe99d4.jpg)

**Comment by gmherr2** [comment]
I did end up working on this issue and added some changes last update but have no way to test this defect, is it still occurring?

**Comment by TechnoSparks** [comment]
Closed because priories should be given to other aspects of the app
