### ISSUE TITLE
[Bug] Back, home, and overview buttons disappear when expanding on quick reply bubble

### ISSUE THREAD

**Issue by MrNuhwin** [gmherr2/AwSMS_IssueTracker#36]
AwSMS Version: Beta 1.2.1 RC3
Device: Moto X Pure
Android Version: 6.0.0

I have an issue where expanding on the quick reply bubble to bring up the keyboard removes my capacitive  back, home, and overview buttons. They come back if I compress the quick reply bubble to just the text message. Is there a reason why those buttons disappear? I feel like they should always be there. 

![unable to minimize screen](https://cloud.githubusercontent.com/assets/19656055/15658725/c16834b0-2674-11e6-9590-e395832393f2.png)

**Comment by gmherr2** [comment]
This is not a bug..... Its the only way to allow it to appear on the lockscreen and appear over other apps without stopping them.
