### ISSUE TITLE
Crash when sharing from picture app

### ISSUE THREAD

**Issue by branpadilla** [gmherr2/AwSMS_IssueTracker#5]
Beta 1.1
Nexus 6P, unrooted, 6.0.1
When sending someone a picture through any picture app, the quick send box crashes upon typing out a contact's name. The message box only seems to close if you type more than one letter when specifying the picture recipient. If I only type in the first letter of the contact and select the contact from the list, I'm able to successfully send the picture without a crash. After successfully picking a recipient, I'm able to type out whatever I want in the text box and the box remains stable.

**Comment by branpadilla** [comment]
Here is an example: https://goo.gl/photos/5cBydTmkDuy5ndHe9

**Comment by gmherr2** [comment]
Is this still an issue for you after the most recent update?

**Comment by branpadilla** [comment]
Completely fixed. Thank you.
